# conda package from https://hub.docker.com/r/mumichae/scib-base
name: scintegration
channels:
 - conda-forge
dependencies:
 - python=3.8
 - ipykernel
 - r-biocmanager
 - rpy2=3.4.5
 - pip
 - pip:
   - scib==1.0.0
   - fa2
   - pyensembl
