# conda package from https://hub.docker.com/r/mumichae/scib-base
name: scintegration
channels:
 - conda-forge
dependencies:
 - python=3.8
 - ipykernel
 - r-biocmanager # Bioconductor version 3.10
 - rpy2=3.4.5
 - pip
 - pip:
   # works for regular pip packages
   - scib==1.0.0
